### PR TITLE
Basic aimbot + some fixes

### PR DESCRIPTION
**Pull request by hvhbot**

### CODE REVIEW

**Comment by denizdeni** [comment]
why you iterate all of entities? you can use client number for players.

**Comment by xAkiraMiura** [comment]
it works but have fun having a lot of accounts untrusted

**Comment by anarh1st47** [comment]
Hello, first of all, thanks for fixing indexes, i'll update it. 

Sorry but i dont see reason to merge aimbot atleast without fixing issues which was related in previous comments(normalizing angles and iterating by all entities. Also why are you taking cmd as argument but dont set angles to cmd? trasing directly in aimbot function should be moved to  CanHit function. Also how it can be used without bind or fov? Yeah, its base, not a full cheat, but features in it should work. Its not possible to play with this aimbot.

**Comment by numero69** [comment]
Hello. I do not see any point in adding an aimbot to this project, since it is mostly meant as a base. However, I will be editing some ESP features so people will see how can they customize this.

**Comment by anarh1st47** [comment]
This aimbot is still useless

**Pull request closed without merging**
