### PR TITLE
Updated Entity virtual methods indices, updated CCSWeaponInfo struct

### PR DESCRIPTION
**Pull request by krll-kov**

### CODE REVIEW

**Comment by hinqiwame** [comment]
still crashing :(

**Comment by krll-kov** [comment]
> still crashing :(

No crashes for me, make sure that you checkout this pull request, not the official branch 
image

**Review by xsoma — APPROVED** [review]

**Comment by alooftr** [comment]
still crashing @xsoma @kirill-21

**Comment by krll-kov** [comment]
> still crashing @xsoma @kirill-21

Works more than perfect for me, you just build from the official repository, not from this pull request, that's the issue.  
image

**Comment by alooftr** [comment]
> > still crashing @xsoma @kirill-21
> 
> Works more than perfect for me, you just build from the official repository, not from this pull request, that's the issue.  
> image
> 

I'm using csgosimple base with millionware menu, I have it in my account, it still crashes.

**Comment by krll-kov** [comment]
> I'm using csgosimple base with millionware menu, I have it in my account, it still crashes.

Why should we even answer you if your question is not about this repository?

**Comment by physmem** [comment]
thank you sir

**Review by rxvan — APPROVED** [review]

**Comment by qicide** [comment]
Wow, this so hard!!

**Comment by rxvan** [comment]
> Wow, this so hard!! If u really think about this what u best coder ever if u edit offset +1, u rly stupid

bro he just made a PR… stop crying on github omg

**Comment by qicide** [comment]
> > Wow, this so hard!! If u really think about this what u best coder ever if u edit offset +1, u rly stupid
> 
> bro he just made a PR… stop crying on github omg

bro then i had bad mood, sry

**Comment by anxiety9001** [comment]
Hey, can u post new fix?

**Comment by krll-kov** [comment]
Updated for 01.18.22

**Comment by anatoriaaa** [comment]
we needs your update!

**Pull request closed without merging**
