### PR TITLE
fixes #16 and #21

### LINKED ISSUE #16: Menu Bug
If you repeatedly press on the background, the weapon will start shooting. Fix it. Thanks.

### PR DESCRIPTION
**Pull request by ultramemer**
keep in mind that i did not test this, but it works in my other cheats

### CODE REVIEW

**Comment by ultramemer** [comment]
also i'm unsure if you need to do the same thing for IN_ATTACK2

**Comment by anarh1st47** [comment]
Yeah, this should works, also maybe check is cursor locked will works too


I'll check it asap, but all looks fine, thanks

**Comment by anarh1st47** [comment]
about attack2: sometimes when i open menu my player continues walking, so, i think best solution is forcing buttons to zero

**Comment by anarh1st47** [comment]
nah bug with movement cannot be fixed by this, sad

**Pull request merged**
